### ISSUE TITLE
RN59+ compatibility

### ISSUE THREAD

**Issue by jimji1005** [kosiakMD/apollo-enchanted-cache-inmemory#1]
Great library! Thanks for the contribution! 

I am in need of upgrading my RN to version 60 but am encountering issues with this library. Can you make some updates to it to not use AsyncStorage from RN core instead use the community AsyncStorage for RN59+?

Thanks @kosiakMD !!

**Comment by kosiakMD** [comment]
@jimji1005 big thanks for your feedback
I'm on my way to make it real It should be in `v1.2.0`, but it's not ready yet
you can try Beta versions, e.g.
https://www.npmjs.com/package/apollo-enchanted-cache-inmemory/v/1.2.0-beta.0
As soon as it will be ready, I'll ping you

**Comment by kosiakMD** [comment]
Done in `v1.2.0`
